# Generate samplesheet for trisomy detection

## 20260123

Generate a samplesheet for all cfDNA samples before, data batch:

2025: before0819/0930/1015/1031/1106/1122/1128/1219/1226

2026: 0107/0109/0115

In [52]:
# Clear up old samplesheet

import pandas as pd

black_list = [
    'PTAY0691P6S1', 
    'PTAY0680P8S1',
    'PTAY0703P9S1',
    'PTAY0560P8S1',
    'PTAY1179P10S1', 
    'PTAY1219P12S1',
    'D5',
    'D6',
    'F7',
    'M8'
]

meta_df_list = []
mqres_df_list = []

# mqres_to_zscore and meta
for batch in ['20251107', '20251113', '20251122', '20251219', '20251226']:
    mqres_df = pd.read_csv(f'../../snp_nipt/data/220k_panel/mqres_to_pileup/{batch}_mqres_samplesheet.csv').dropna(axis=0)

    # Combine {sample}C and {sample}A together
    if batch == '20260121':
        mqres_df['sample'] = mqres_df['sample'].apply(lambda x: x[:-1] if x.endswith(('C', 'A')) else x)

    mqres_df_list.append(mqres_df)

meta_df = pd.read_csv('../../snp_nipt/results/220k_panel/summary/usable_clean_samplesheet.csv', usecols=['sample', 'label', 'week']).dropna(axis=0)
meta_df_list.append(meta_df)

for batch in ['20260109', '20260121', '20260115']:
    meta_df = pd.read_csv(f'../../snp_nipt/data/220k_panel/mqres_to_pileup/{batch}_meta.tsv', sep='\t', usecols=['sample', 'label', 'week']).dropna(axis=0)
    mqres_df = pd.read_csv(f'../../snp_nipt/data/220k_panel/mqres_to_pileup/{batch}_mqres_samplesheet.csv').dropna(axis=0)

    # Combine {sample}C and {sample}A together
    if batch == '20260121':
        meta_df['sample'] = meta_df['sample'].apply(lambda x: x[:-1] if x.endswith(('C', 'A')) else x)
        mqres_df['sample'] = mqres_df['sample'].apply(lambda x: x[:-1] if x.endswith(('C', 'A')) else x)

    # Combine {sample}_A and {sample}_X together
    if batch == '20260115':
        mqres_df['sample'] = mqres_df['sample'].apply(lambda x: x[:-2] if x.endswith(('A', 'X')) else x)

    meta_df_list.append(meta_df)
    mqres_df_list.append(mqres_df)

meta_df = pd.read_csv('../../snp_nipt/data/220k_panel/mqres_to_pileup/dropped_meta.tsv', sep='\t', usecols=['sample', 'label', 'week']).dropna(axis=0)
meta_df_list.append(meta_df)

meta_df = pd.concat(meta_df_list, axis=0)
mqres_df = pd.concat(mqres_df_list, axis=0)

meta_df = meta_df[~meta_df['sample'].isin(black_list)].reset_index(drop=True)
meta_df.drop_duplicates(inplace=True)

mqres_df = mqres_df[~mqres_df['sample'].isin(black_list)].reset_index(drop=True)
mqres_df.rename(columns={'bam': 'clean_bam', 'txt': 'deconv_res'}, inplace=True)
mqres_df = mqres_df[['sample', 'clean_bam', 'deconv_res']]

meta_df.to_csv('../../snp_nipt/data/220k_panel/mqres_to_zscore/20260123_meta.tsv', sep='\t', index=False)

early_sample_list = meta_df[meta_df['week'] <= 12]['sample'].unique()
middle_sample_list = meta_df[meta_df['week'] > 12]['sample'].unique()

early_mqres_df = mqres_df[mqres_df['sample'].isin(early_sample_list)]
middle_mqres_df = mqres_df[mqres_df['sample'].isin(middle_sample_list)]

# Rename bam path for 0930/1015/1031 due to T7 naming format
bam_path = '/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/20250930-XML/bwameth_results/bam_rmdup'
early_mqres_df['clean_bam'] = early_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if 'E2501' in x['clean_bam'] else x['clean_bam'], axis=1)

bam_path = '/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/20251015-XML/bwameth_results/bam_rmdup'
early_mqres_df['clean_bam'] = early_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251015' in x['clean_bam'] else x['clean_bam'], axis=1)

bam_path = '/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/20251031-XML/bwameth_results/bam_rmdup'
early_mqres_df['clean_bam'] = early_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251031' in x['clean_bam'] else x['clean_bam'], axis=1)

bam_path = '/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/20250930-XML/bwameth_results/bam_rmdup'
middle_mqres_df['clean_bam'] = middle_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if 'E2501' in x['clean_bam'] else x['clean_bam'], axis=1)

bam_path = '/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/20251015-XML/bwameth_results/bam_rmdup'
middle_mqres_df['clean_bam'] = middle_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251015' in x['clean_bam'] else x['clean_bam'], axis=1)

bam_path = '/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/20251031-XML/bwameth_results/bam_rmdup'
middle_mqres_df['clean_bam'] = middle_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251031' in x['clean_bam'] else x['clean_bam'], axis=1)

early_mqres_df.to_csv('../../snp_nipt/data/220k_panel/mqres_to_zscore/20260123_early_mqres_samplesheet.csv', index=False)
middle_mqres_df.to_csv('../../snp_nipt/data/220k_panel/mqres_to_zscore/20260123_middle_mqres_samplesheet.csv', index=False)

/tmp/ipykernel_252853/2046484458.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  early_mqres_df['clean_bam'] = early_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if 'E2501' in x['clean_bam'] else x['clean_bam'], axis=1)
/tmp/ipykernel_252853/2046484458.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  early_mqres_df['clean_bam'] = early_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251015' in x['clean_bam'] else x['clean_bam'], axis=1)
/tmp/ipykernel_252853/2046484458.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  early_mqres_df['clean_bam'] = early_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251031' in x['clean_bam'] else x['clean_bam'], axis=1)
/tmp/ipykernel_252853/2046484458.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  middle_mqres_df['clean_bam'] = middle_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if 'E2501' in x['clean_bam'] else x['clean_bam'], axis=1)
/tmp/ipykernel_252853/2046484458.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  middle_mqres_df['clean_bam'] = middle_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251015' in x['clean_bam'] else x['clean_bam'], axis=1)
/tmp/ipykernel_252853/2046484458.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  middle_mqres_df['clean_bam'] = middle_mqres_df.apply(lambda x: f'{bam_path}/{x["sample"]}.clean.bam' if '20251031' in x['clean_bam'] else x['clean_bam'], axis=1)

## 20260127

Generate a samplesheet for resequenced 4 samples, 3 unknown samples and 6 unknown samples in different experiment conditions(_A, _H).

Data batch: 20260120

Resequenced samples in batch: 20250930/20251015/20251226

In [19]:
reseq_sample_list = [
    'PTAY0577P9S1',
    'PTAY0620P8S1',
    'PTAY1024P8S1',
    'PTAY1186P8S1'
]

data_batch = [
    '20250930',
    '20251015',
    '20251226',
    '20260120'
]

# mqres samplesheet
import pandas as pd
import os
import glob
import re

meta = []

for batch in data_batch:
    mqres_dir_path = f'/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/{batch}-XML/bwameth_results/mq_downstream'

    pattern = re.compile(r"^(?P<sample>[^_]+)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in reseq_sample_list:          
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

    pattern = re.compile(r"single_end_(?P<sample>.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in reseq_sample_list:           
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

for batch in ['20260120']:
    mqres_dir_path = f'/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/{batch}-XML/bwameth_results/mq_downstream'

    pattern = re.compile(r"^(?P<sample>PTAY.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample not in reseq_sample_list:          
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

    pattern = re.compile(r"single_end_(?P<sample>.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample not in reseq_sample_list:           
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

meta_df = pd.DataFrame(meta)

meta_df = meta_df[meta_df['sample'] != 'M8']
meta_df = meta_df[~meta_df['sample'].str.contains('UMBS')]

output_samplesheet = '/lustre1/cqyi/syfan/snp_nipt/data/220k_panel/mqres_to_zscore/20260127_mqres_samplesheet.csv'
meta_df.to_csv(output_samplesheet, index=False)

## 20260210

Generate a samplesheet for UMBS samples PTAY1102P7H1,PTAY1170P8S1

Data batch: 20260203

Resequenced samples in batch: 20251226

Generate a samplesheet for experiment exploration samples with different suffixes('_A', '_H'):
PTAY0965P8S1
PTAY0967P8S1
PTAY0988P7S1
PTAY1001P9S1
PTAY1102P7H1
PTAY1160P8S1
PTAY1177P8S1

Data batch: 20260203

In [3]:
reseq_sample_list = [
    'PTAY1102P7H1',
    'PTAY1170P8S1',
    'PTAY1102P7H1_UMBS',
    'PTAY1170P8S1_UMBS'
]

data_batch = [
    '20251226',
    '20260203'
]

# mqres samplesheet
import pandas as pd
import os
import glob
import re

meta = []

for batch in data_batch:
    mqres_dir_path = f'/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/{batch}-XML/bwameth_results/mq_downstream'

    pattern = re.compile(r"^(?P<sample>PTAY.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in reseq_sample_list:          
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

    pattern = re.compile(r"single_end_(?P<sample>.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in reseq_sample_list:           
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

meta_df = pd.DataFrame(meta)

output_samplesheet = '/lustre1/cqyi/syfan/snp_nipt/data/220k_panel/mqres_to_zscore/20260203_mqres_samplesheet.csv'
meta_df.to_csv(output_samplesheet, index=False)

In [7]:
sample_list = [
    'PTAY0965P8S1_A',
    'PTAY0967P8S1_A',
    'PTAY0988P7S1_A',
    'PTAY1001P9S1_A',
    'PTAY1102P7H1_A',
    'PTAY1160P8S1_A',
    'PTAY1177P8S1_A',
    'PTAY0965P8S1_H',
    'PTAY0967P8S1_H',
    'PTAY0988P7S1_H',
    'PTAY1001P9S1_H',
    'PTAY1102P7H1_H',
    'PTAY1160P8S1_H',
    'PTAY1177P8S1_H'
]

data_batch = [
    '20260203'
]

# mqres samplesheet
import pandas as pd
import os
import glob
import re

meta = []

for batch in data_batch:
    mqres_dir_path = f'/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/{batch}-XML/bwameth_results/mq_downstream'

    pattern = re.compile(r"^(?P<sample>PTAY.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in sample_list:
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

    pattern = re.compile(r"single_end_(?P<sample>.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in sample_list:           
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                sample = sample.split('-')[0]

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

meta_df = pd.DataFrame(meta)

output_samplesheet = '/lustre1/cqyi/syfan/snp_nipt/data/220k_panel/mqres_to_zscore/20260203_exp_mqres_samplesheet.csv'
meta_df.to_csv(output_samplesheet, index=False)

## 20260308

cfm samples

In [21]:
from tokenize import String
import pandas as pd
import os

mq_dir = '/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/0306_run_from_bam/bwameth_results/mq_downstream'
dir_list = [i for i in os.listdir(mq_dir) if 'testres' in i]

samplesheet_df = pd.read_csv('/lustre1/cqyi/syfan/snp_nipt/data/220k_panel/bam_to_pileup/cfdna_vs_cfm/cfm_samplesheet.csv')

expanded_rows = []
for _, row in samplesheet_df.iterrows():
    sample = str(row['bam']).split('/')[-1].split('.')[0]
    matched_dirs = [d for d in dir_list if sample in d]
    if matched_dirs:
        for d in matched_dirs:
            new_row = row.copy()
            new_row['deconv_res'] = f'{mq_dir}/{d}/test_res.txt'
            expanded_rows.append(new_row)
    else:
        continue

expanded_samplesheet_df = pd.DataFrame(expanded_rows)
expanded_samplesheet_df['sample'] = expanded_samplesheet_df['sample'].astype(str)
expanded_samplesheet_df['bam'] = expanded_samplesheet_df['bam'].astype(str)
expanded_samplesheet_df['deconv_res'] = expanded_samplesheet_df['deconv_res'].astype(str)
expanded_samplesheet_df = expanded_samplesheet_df.rename(columns={'bam':'clean_bam'})

expanded_samplesheet_df.to_csv('/lustre1/cqyi/syfan/snp_nipt/data/220k_panel/mqres_to_zscore/20260308_cfm_mqres_samplesheet.csv', index=False)

## 20260330

Rerun PTAY1351P8S1 -A -C

In [4]:
reseq_sample_list = [
    'PTAY1351P8S1-C',
    'PTAY1351P8S1-A',
]

data_batch = [
    '20260327',
]

# mqres samplesheet
import pandas as pd
import os
import glob
import re

meta = []

for batch in data_batch:
    mqres_dir_path = f'/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/{batch}-XML/bwameth_results/mq_downstream'

    pattern = re.compile(r"^(?P<sample>PTAY.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in reseq_sample_list:          
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

    pattern = re.compile(r"single_end_(?P<sample>.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            if sample in reseq_sample_list:           
                txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
                bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

                if os.path.exists(txt_path) and os.path.exists(bam_path):
                    meta.append({
                        'sample': sample,
                        'deconv_res': txt_path,
                        'clean_bam': bam_path
                    })
                else:
                    print(bam_path)

meta_df = pd.DataFrame(meta)

output_samplesheet = '/lustre1/cqyi/syfan/snp_nipt/data/220k_panel/mqres_to_zscore/20260330_mqres_samplesheet.csv'
meta_df.to_csv(output_samplesheet, index=False)

meta_df

,sample,deconv_res,clean_bam
0,PTAY1351P8S1-A,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
1,PTAY1351P8S1-C,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
2,PTAY1351P8S1-A,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
3,PTAY1351P8S1-C,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...

## 20260401

Run 20260322 data batch (240k panel samples)

In [6]:
data_batch = [
    '20260322-240k',
]

# mqres samplesheet
import pandas as pd
import os
import glob
import re

meta = []

for batch in data_batch:
    mqres_dir_path = f'/appsnew/home/myli/lustre1/bert/DNA_5mC_analysis_pipeline/output/{batch}/bwameth_results/mq_downstream'

    pattern = re.compile(r"^(?P<sample>PTAY.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
            bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

            if os.path.exists(txt_path) and os.path.exists(bam_path):
                meta.append({
                    'sample': sample,
                    'deconv_res': txt_path,
                    'clean_bam': bam_path
                })
            else:
                print(bam_path)

    pattern = re.compile(r"single_end_(?P<sample>PTAY.*)_input.bed.gz_testres$")

    for res_dir in os.listdir(mqres_dir_path):
        match = pattern.match(res_dir)

        if match:
            sample = match.group('sample')
            txt_path = os.path.join(mqres_dir_path, res_dir, 'test_res.txt')
            bam_path = os.path.join(mqres_dir_path, '../bam_rmdup', f'{sample}.clean.bam')

            if os.path.exists(txt_path) and os.path.exists(bam_path):
                meta.append({
                    'sample': sample,
                    'deconv_res': txt_path,
                    'clean_bam': bam_path
                })
            else:
                print(bam_path)

meta_df = pd.DataFrame(meta)

output_samplesheet = '/lustre1/cqyi/syfan/snp_nipt/data/240k_panel/samplesheet/20260401_mqres_samplesheet.csv'
meta_df.to_csv(output_samplesheet, index=False)

meta_df

,sample,deconv_res,clean_bam
0,PTAY0687P18H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
1,PTAY0459P19H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
2,PTAY0473P19H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
3,PTAY0461P21H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
4,PTAY0460P20H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
...,...,...,...
77,PTAY0449P24H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
78,PTAY0488P22H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
79,PTAY0549P19H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
80,PTAY0496P23H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...
81,PTAY0564P25H1,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...,/appsnew/home/myli/lustre1/bert/DNA_5mC_analys...

## 20260403

Build json input for adjusted_zscore/adjusted_episcore

In [ ]:
# Adjust

from feishu_helper import *

bitable_df = read_bitable()

samples_to_fit_df = bitable_df[
    (bitable_df['label'] == 'Normal') &
    ()
]

[Lark] [2026-04-03 16:49:54,810] [DEBUG] POST https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal 200, headers: {"User-Agent": "oapi-sdk-python/v1.5.3"}, params: [], body: {"app_id": "cli_a9f29a1939395bcd", "app_secret": "eO2MA3gtY69PTsoGW4gvJhNZv4cWT8E7"}

DEBUG:Lark:POST https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal 200, headers: {"User-Agent": "oapi-sdk-python/v1.5.3"}, params: [], body: {"app_id": "cli_a9f29a1939395bcd", "app_secret": "eO2MA3gtY69PTsoGW4gvJhNZv4cWT8E7"}

[Lark] [2026-04-03 16:49:56,221] [DEBUG] POST https://open.feishu.cn/open-apis/bitable/v1/apps/TLEcbPKaAaGpi4sYXxhcOtWCnZe/tables/tbl6GWTC5UDBaUSk/records/search 200, headers: {"User-Agent": "oapi-sdk-python/v1.5.3", "Content-Type": "application/json; charset=utf-8", "Authorization": "Bearer t-g10443gNQPTMMJXSCWYLX3WKJIANK56IXH5JZ2TM"}, params: [["page_size", "500"], ["page_token", ""]], body: {"view_id": "vewP795m6y", "automatic_fields": false}

DEBUG:Lark:POST https://open.feishu.cn/open-apis/bitable/v1/apps/TLEcbPKaAaGpi4sYXxhcOtWCnZe/tables/tbl6GWTC5UDBaUSk/records/search 200, headers: {"User-Agent": "oapi-sdk-python/v1.5.3", "Content-Type": "application/json; charset=utf-8", "Authorization": "Bearer t-g10443gNQPTMMJXSCWYLX3WKJIANK56IXH5JZ2TM"}, params: [["page_size", "500"], ["page_token", ""]], body: {"view_id": "vewP795m6y", "automatic_fields": false}

,age,beta_zscores,conception_mode,cpg_mean_coverage,depth_qc,ff_after_mq,ff_before_mq,final_zscores,label,mean_target_coverage,...,sample,set,snp_mean_coverage,state,timepoint,week,HCG,conservative_match_status,match_status,purity
0,41.0,"0.072222,-0.772502,0.781072,-0.336707,0.077929...",自然,206.939224,pass,0.017,0.003,"-0.0649362585046351,-0.503526330951661,-0.8448...",Unknown,166.312481,...,JPTAY1379P6H1,test,52.650418,妊娠,2026-01-22,6.0,NaN,NaN,NaN,NaN
1,31.0,"1.983162,0.361621,-2.367317,0.049543,-1.372707...",TET,66.866519,fail,0.155,0.049,"1.7028744689117103,-0.3128397429585389,-1.7291...",Normal,56.133973,...,PTAY0521P6H1,dev,18.613096,妊娠,2025-04-26,6.0,67576.0,match,mismatch,NaN
2,30.0,"1.0407,-0.287583,-1.133406,-0.718285,0.28982,-...",促排,94.553930,pass,0.140,0.044,"1.1329232679948882,0.2298652658590213,-0.03148...",Normal,82.729491,...,PTAY0530P6H1,dev,29.046390,妊娠,2025-04-29,6.0,49075.0,match,match,NaN
3,30.0,"0.432925,-0.26,0.387983,0.034167,-0.084479,0.4...",自然,153.641434,pass,0.127,0.034,"0.9433970766088872,-0.6144009866464498,-0.1073...",Normal,129.654793,...,PTAY0527P6H1,dev,43.336632,妊娠,2025-04-28,6.0,69403.0,match,match,NaN
4,30.0,"0.719128,0.1424,1.567662,0.758295,-1.328909,1....",TET,146.640633,pass,0.068,0.013,"1.978238000448837,1.0091651510746131,0.6384941...",Unknown,119.254812,...,PTAY0518P6H1,test,37.973722,妊娠,2025-04-25,6.0,29240.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,NaN,"1.012618,0.45549,0.044763,0.917095,0.15334,0.8...",NaN,146.599708,pass,0.031,0.007,"1.4882709941076455,1.025006556450992,0.5053603...",T16,0.000000,...,PTAY1316P7S1,dev,46.137597,胎停,NaT,NaN,NaN,mismatch,mismatch,NaN
457,NaN,"-1.131287,-0.454608,0.85941,1.413408,0.688102,...",NaN,258.016147,pass,0.029,0.006,"-0.8677167422797135,-0.8966465329073313,-0.273...",Normal,0.000000,...,PTAY1330P7S1,dev,70.705634,胎停,NaT,NaN,NaN,match,mismatch,NaN
458,NaN,"-0.0665,-0.025806,0.453269,0.523416,1.874452,-...",NaN,168.275485,pass,0.076,0.019,"0.6036305356935874,0.4564448063033134,0.709440...",Normal,0.000000,...,PTAY1331P8S1,dev,50.565398,胎停,NaT,NaN,NaN,match,match,NaN
459,NaN,"-1.55944,-1.686061,-2.093331,-1.436364,-1.6227...",NaN,57.011140,fail,0.156,0.060,"-1.980577108401266,-0.848706236738809,-1.29119...",T13,0.000000,...,PTAY1334P8S1,dev,18.925789,胎停,NaT,NaN,NaN,match,partially_match,NaN
460,NaN,"-0.018444,0.126204,-0.224461,1.54929,1.643061,...",NaN,208.286714,pass,0.012,0.004,"1.0569323925727665,0.2712298843241411,-0.34073...",T16,0.000000,...,PTAY1340P7S1,dev,58.449982,胎停,NaT,NaN,NaN,mismatch,mismatch,NaN

## JPTAY1538P8H1 sample

In [3]:
import pandas as pd

data = [
    {
        'sample': 'JPTAY1538P8H1-MQ-220k-panel-240k',
        'clean_bam': '/lustre1/cqyi/myli/bert/DNA_5mC_analysis_pipeline/output/20260330-XML/bwameth_results/bam_rmdup/ig240K_JPTAY1538P8H1.clean.bam',
        'deconv_res': '/lustre1/cqyi/myli/bert/DNA_5mC_analysis_pipeline/output/20260330-XML/bwameth_results/mq_downstream/ig240K_JPTAY1538P8H1_input.bed.gz_testres/test_res.txt'
    },
    {
        'sample': 'JPTAY1538P8H1-MQ-220k-panel-220k',
        'clean_bam': '/lustre1/cqyi/myli/bert/DNA_5mC_analysis_pipeline/output/20260330-XML/bwameth_results/bam_rmdup/JPTAY1538P8H1.clean.bam',
        'deconv_res': '/lustre1/cqyi/myli/bert/DNA_5mC_analysis_pipeline/output/20260330-XML/bwameth_results/mq_downstream/JPTAY1538P8H1_input.bed.gz_testres/test_res.txt'
    },
    {
        'sample': 'JPTAY1538P8H1-MQ-240k-panel-240k',
        'clean_bam': '/lustre1/cqyi/myli/bert/DNA_5mC_analysis_pipeline/output/20260330-240k/bwameth_results/bam_rmdup/ig240K_JPTAY1538P8H1.clean.bam',
        'deconv_res': '/lustre1/cqyi/myli/bert/DNA_5mC_analysis_pipeline/output/20260330-240k/bwameth_results/mq_downstream/ig240K_JPTAY1538P8H1_input.bed.gz_testres/test_res.txt'
    }
]

pd.DataFrame(data).to_csv('/lustre1/cqyi/syfan/nf_autogluon_infer/data/240k_panel/JPTAY1538P8H1_mqres_samplesheet.csv', index=False)